fix build ERROR: unsatisfiable constraints
simply remove them away

ERROR: unsatisfiable constraints:
  bzr (missing):
    required by: world[bzr]
  fossil (missing):
    required by: world[fossil]

ERROR: unsatisfiable constraints:
  fossil (missing):
    required by: world[fossil]